apiVersion: v1
kind: Secret
metadata:
  name: ai-interview-secrets
  namespace: ai-interview
type: Opaque
stringData:
  secret-key: "30c1c7e44b45be060fd6bd1edd438fc8f45116b390db37c1bb9b48a67fd53b50"
  database-url: "postgresql://interview_user:interview_password@postgres:5432/interview_db"
  postgres-user: "interview_user"
  postgres-password: "interview_password"
  postgres-db: "interview_db"
  allowed-origins: "http://192.168.174.146,http://192.168.174.147,http://192.168.174.148"