apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ai-interview
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        node-role: worker
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: backend
      containers:
        - name: backend
          image: othmansalahi/ai-voice-interview-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-interview-secrets
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-interview-secrets
                  key: secret-key
            - name: PORT
              value: "8000"
            - name: WORKERS
              value: "1"
            - name: LOG_LEVEL
              value: "info"
            - name: ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: ai-interview-secrets
                  key: allowed-origins
            - name: KB_FILE
              value: "/app/final_knowledge_base.csv"
            - name: COURSES_FILE
              value: "/app/course_catalog.csv"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              memory: "768Mi"
              cpu: "250m"
            limits:
              memory: "1.5Gi"
              cpu: "750m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ai-interview
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
