apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ai-interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        node-role: worker
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: frontend
      containers:
        - name: frontend
          image: othmansalahi/ai-voice-interview-frontend:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - sed -i 's/\r$//' /docker-entrypoint.d/40-runtime-config.sh 2>/dev/null || true; chmod +x /docker-entrypoint.d/40-runtime-config.sh 2>/dev/null || true; exec /docker-entrypoint.sh nginx -g 'daemon off;'
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ai-interview
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
